In [1]:
import numpy as np
import pandas as pd

In [2]:
X = pd.read_csv("cup98lrn.txt")

/var/folders/2z/dxb5rnhd7wx6yg77m3z4c1n40000gn/T/ipykernel_62460/3700503834.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  X = pd.read_csv("cup98lrn.txt")


In [3]:
X

ODATEDW OSOURCE  TCODE STATE    ZIP MAILCODE PVASTATE   DOB NOEXCH  \
0         8901     GRI      0    IL  61081                    3712      0   
1         9401     BOA      1    CA  91326                    5202      0   
2         9001     AMH      1    NC  27017                       0      0   
3         8701     BRY      0    CA  95953                    2801      0   
4         8601              0    FL  33176                    2001      0   
...        ...     ...    ...   ...    ...      ...      ...   ...    ...   
95407     9601     ASE      1    AK  99504                       0      0   
95408     9601     DCD      1    TX  77379                    5001      0   
95409     9501     MBC      1    MI  48910                    3801      0   
95410     8601     PRV      0    CA  91320                    4005      0   
95411     8801     MCC      2    NC  28409                    1801      0   

      RECINHSE  ... TARGET_D HPHONE_D RFA_2R RFA_2F RFA_2A MDMAUD_R  MDMAUD_F  \
0               ...      0.0        0      L      4      E        X         X   
1               ...      0.0        0      L      2      G        X         X   
2               ...      0.0        1      L      4      E        X         X   
3               ...      0.0        1      L      4      E        X         X   
4            X  ...      0.0        1      L      2      F        X         X   
...        ...  ...      ...      ...    ...    ...    ...      ...       ...   
95407           ...      0.0        0      L      1      G        X         X   
95408           ...      0.0        1      L      1      F        X         X   
95409           ...      0.0        1      L      3      E        X         X   
95410        X  ...     18.0        1      L      4      F        X         X   
95411        X  ...      0.0        1      L      1      G        C         1   

      MDMAUD_A CLUSTER2 GEOCODE2  
0            X     39.0        C  
1            X      1.0        A  
2            X     60.0        C  
3            X     41.0        C  
4            X     26.0        A  
...        ...      ...      ...  
95407        X     12.0        C  
95408        X      2.0        A  
95409        X     34.0        B  
95410        X     11.0        A  
95411        C     12.0        C  

[95412 rows x 481 columns]

In [7]:
pd.options.display.max_rows = 500
X.isna().sum()

ODATEDW         0
OSOURCE         0
TCODE           0
STATE           0
ZIP             0
MAILCODE        0
PVASTATE        0
DOB             0
NOEXCH          0
RECINHSE        0
RECP3           0
RECPGVG         0
RECSWEEP        0
MDMAUD          0
DOMAIN          0
CLUSTER         0
AGE         23665
AGEFLAG         0
HOMEOWNR        0
CHILD03         0
CHILD07         0
CHILD12         0
CHILD18         0
NUMCHLD     83026
INCOME      21286
GENDER          0
WEALTH1     44732
HIT             0
MBCRAFT     52854
MBGARDEN    52854
MBBOOKS     52854
MBCOLECT    52914
MAGFAML     52854
MAGFEM      52854
MAGMALE     52854
PUBGARDN    52854
PUBCULIN    52854
PUBHLTH     52854
PUBDOITY    52854
PUBNEWFN    52854
PUBPHOTO    52854
PUBOPP      52854
DATASRCE        0
MALEMILI        0
MALEVET         0
VIETVETS        0
WWIIVETS        0
LOCALGOV        0
STATEGOV        0
FEDGOV          0
SOLP3           0
SOLIH           0
MAJOR           0
WEALTH2     43823
GEOCODE         0
COLLECT1  

In [13]:
# Taken from https://github.com/rebordao/kdd98cup/blob/cc147edb00ad9e6b4333591585b0b5e771318dcf/lib/preprocessor.py

import numpy as np
import pandas as pd
from sklearn.base import TransformerMixin

class Preprocessor:
    @staticmethod
    def fill_nans(dat):
        '''
        Fills in NaNs with either the mean or the most common value.
        '''

        return DataFrameImputer().fit_transform(dat)

class DataFrameImputer(TransformerMixin):
    '''
    This class came from http://stackoverflow.com/questions/25239958/
    impute-categorical-missing-values-in-scikit-learn
    '''

    def __init__(self):
        '''
        Impute missing values.
        Columns of dtype object are imputed with the most frequent value in col.
        Columns of other types are imputed with mean of column.
        '''

    def fit(self, X, y = None):
        self.fill = pd.Series(
            [X[c].value_counts().index[0] if X[c].dtype == np.dtype('O') else X[c].mean() for c in X],
            index = X.columns
        )
        return self

    def transform(self, X, y = None):
        return X.fillna(self.fill)

In [14]:
imputed_X = Preprocessor.fill_nans(X)

In [16]:
imputed_X.isna().sum().sum()

0

In [21]:
pd.options.display.max_rows = 500
imputed_X.TARGET_D[:500]

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      4.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
30      7.0
31      0.0
32      0.0
33      0.0
34      0.0
35      0.0
36      0.0
37      0.0
38      0.0
39      0.0
40      0.0
41      0.0
42      0.0
43      0.0
44      0.0
45      5.0
46      0.0
47      0.0
48      0.0
49      0.0
50      0.0
51      0.0
52      0.0
53      0.0
54      0.0
55      0.0
56      0.0
57      0.0
58      0.0
59      0.0
60      0.0
61      0.0
62      0.0
63      0.0
64      0.0
65      0.0
66      0.0
67      0.0
68      0.0
69      0.0
70      0.0
71      0.0
72      0.0
73      0.0
74      0.0
75      0.0
76      0.0
77      0.0
78     13.0
79      0.0
80      0.0
81      0.0
82      0.0
83  

In [24]:
imputed_X.to_numpy()

array([[8901, 'GRI', 0, ..., 'X', 39.0, 'C'],
       [9401, 'BOA', 1, ..., 'X', 1.0, 'A'],
       [9001, 'AMH', 1, ..., 'X', 60.0, 'C'],
       ...,
       [9501, 'MBC', 1, ..., 'X', 34.0, 'B'],
       [8601, 'PRV', 0, ..., 'X', 11.0, 'A'],
       [8801, 'MCC', 2, ..., 'C', 12.0, 'C']], dtype=object)

In [25]:
np.save("kdd98.npz", imputed_X) 

In [28]:
imputed_X.columns.get_loc("TARGET_D")

471

In [29]:
imputed_X.shape

(95412, 481)

In [39]:
X = np.random.rand(5,5)
print(X)
print()
y = X[:, 3]
print(y)
print()
X = np.delete(X, 3, 1)
print(X)
print()
print(y)
print()

[[0.7475214  0.60827871 0.53449596 0.36515479 0.42471023]
 [0.21943461 0.1276166  0.2941656  0.29001811 0.04050938]
 [0.31247532 0.32497529 0.01317497 0.59915246 0.2690759 ]
 [0.76579623 0.79314462 0.99608231 0.53880314 0.45269339]
 [0.72739929 0.31558673 0.52416283 0.46466828 0.63390908]]

[0.36515479 0.29001811 0.59915246 0.53880314 0.46466828]

[[0.7475214  0.60827871 0.53449596 0.42471023]
 [0.21943461 0.1276166  0.2941656  0.04050938]
 [0.31247532 0.32497529 0.01317497 0.2690759 ]
 [0.76579623 0.79314462 0.99608231 0.45269339]
 [0.72739929 0.31558673 0.52416283 0.63390908]]

[0.36515479 0.29001811 0.59915246 0.53880314 0.46466828]



In [46]:
rng = np.random.default_rng()
rng.shuffle(X) # in-place
X

array([[0.76579623, 0.79314462, 0.99608231, 0.45269339],
       [0.31247532, 0.32497529, 0.01317497, 0.2690759 ],
       [0.72739929, 0.31558673, 0.52416283, 0.63390908],
       [0.7475214 , 0.60827871, 0.53449596, 0.42471023],
       [0.21943461, 0.1276166 , 0.2941656 , 0.04050938]])

In [43]:
X

array([[0.21943461, 0.1276166 , 0.2941656 , 0.04050938],
       [0.31247532, 0.32497529, 0.01317497, 0.2690759 ],
       [0.72739929, 0.31558673, 0.52416283, 0.63390908],
       [0.76579623, 0.79314462, 0.99608231, 0.45269339],
       [0.7475214 , 0.60827871, 0.53449596, 0.42471023]])